name: yfy_invoice_generator
description: To create Voucher easily.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  screenshot: ^1.2.3
  image_gallery_saver: "^1.7.1"
  shared_preferences: ^2.0.15
  localstorage: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Myanmar
      fonts:
        - asset: assets/fonts/Pyidaungsu-Regular.ttf
        - asset: assets/fonts/Pyidaungsu-Bold.ttf
          weight: 700
